config/routes.rb
Rails.application.routes.draw do
  resources :quotations do
    collection do
      get 'export_xml', to: 'quotations#export_xml', defaults: { format: 'xml' }
      get 'export_json', to: 'quotations#export_json', defaults: { format: 'json' }
      post 'import_xml', to: 'quotations#import_xml'
      post 'import_xml_external', to: 'quotations#import_xml_external'
end
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'search_quotations', to: 'quotations#search'

  # Defines the root path route ("/")
 root "quotations#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :quotations
  end
  

app/models/quotation.rb
class Quotation < ApplicationRecord
    attr_accessor :new_category
    belongs_to :category
    validates_presence_of :author_name, :quote
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotations_controller.rb
require 'nokogiri'
require 'open-uri'
require 'rexml/document'


class QuotationsController < ApplicationController
    def index
        @quotations = if params[:query].present?
          search_quotations
        else
          Quotation.all
        end
      end
    

    def new
        @quotation = Quotation.new
        @existing_categories = Category.distinct.pluck(:name).compact
        @existing_categories ||= [] 
      end
          
    def show
        @quotation = Quotation.find(params[:id])
    end
      
    def search
        @query = params[:query].downcase
        @quotations = search_quotations
        render :index
      end
    
      
    
      def export_xml
        @quotations = Quotation.all
    
        # Build the XML document
        xml_builder = Nokogiri::XML::Builder.new do |xml|
          xml.quotations {
            @quotations.each do |quotation|
              xml.quotation {
                xml.author_name quotation.author_name
                xml.category quotation.category.name
                xml.quote quotation.quote
              }
            end
          }
        end
    
        formatted_xml = xml_builder.to_xml(indent: 2)
    
        respond_to do |format|
          format.xml { render xml: formatted_xml }
        end
      end
    
    

      def export_json
        @quotations = Quotation.all
    
        formatted_json = JSON.pretty_generate(JSON.parse(@quotations.to_json))
    
        respond_to do |format|
          format.json { render json: formatted_json }
        end
      end
    
    
      def import_xml_external
        if params[:xml_url].present?
          url = params[:xml_url]
    
          begin
            xml_data = open(url).read
            import_quotations_from_xml(xml_data)
            flash[:notice] = 'Quotations imported successfully'
          rescue OpenURI::HTTPError => e
            flash[:error] = "Error fetching data from the URL: #{e.message}"
          rescue REXML::ParseException => e
            flash[:error] = "Error parsing XML data: #{e.message}"
          end
        else
          flash[:error] = 'Please provide a valid XML URL'
        end
    
        redirect_to quotations_path
      end
    
      def import_xml
        begin
          file_path = Rails.root.join('app', 'views', 'quotations', 'Importxml_test.xml')
          xml_data = File.read(file_path)
          import_quotations_from_xml(xml_data)
          flash[:notice] = 'Quotations imported successfully'
        rescue Errno::ENOENT
          flash[:error] = 'XML file not found'
        rescue REXML::ParseException => e
          flash[:error] = "Error parsing XML data: #{e.message}"
        end
      
        redirect_to quotations_path
      end
      

      
      def create
        @quotation = Quotation.new(quotation_params)
      
        if params[:quotation][:category_id].present?
          # User selected an existing category
          existing_category_id = params[:quotation][:category_id]
          @quotation.category_id = existing_category_id
        else
          # User entered a new category
          if params[:quotation][:new_category].present?
            new_category_name = params[:quotation][:new_category]
            category = Category.create(name: new_category_name)
            @quotation.category_id = category.id
          end
        end
      
        respond_to do |format|
          if @quotation.save
            flash[:notice] = 'Quotation was successfully created'
            format.html { redirect_to @quotation }
          else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @quotation.errors, status: :unprocessable_entity }
          end
        end
      end
      
      
        # ...
      
        private

        def import_quotations_from_xml(xml_data)
            doc = REXML::Document.new(xml_data)
            doc.elements.each('quotations/quotation') do |quotation_element|
              author_name = quotation_element.elements['author_name'].text
              category_name = quotation_element.elements['category'].text
              quote = quotation_element.elements['quote'].text
          
              # Find or create the Category based on the category_name
              category = Category.find_or_create_by(name: category_name)
          
              Quotation.create(author_name: author_name, category: category, quote: quote)
            end
          end
          
        
        def search_quotations
            Quotation.where('quote ILIKE ? OR author_name ILIKE ?', "%#{@query}%", "%#{@query}%")
          end
        
      
        def quotation_params
            params.require(:quotation).permit(:author_name, :quote, :category_id, :new_category)
          end
          
      end
      
      

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotation_helper.rb
module QuotationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quotationapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quotations/_form.html.erb
<%= form_for @quotation, url: { action: "create" } do |form| %>
    <div id="error_explanation">
      <% if @quotation.errors.any? %>
        <h2><%= pluralize(@quotation.errors.count, "error") %> prohibited this quotation from being saved:</h2>
        <ul>
          <% @quotation.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end  %>
<fieldset>
<legend>Enter details</legend>
<div class="form_row">
<%= form.label :author_name %>
<%= form.text_field :author_name, :size => 20, :maxlength => 40 %>
</div>
<br> 
<div class="form_row">
  <%= form.label :category%>
  <%= debug @existing_categories %>

  <%= form.select :category, options_for_select(@existing_categories, @quotation.category), include_blank: 'Select Category' %>
</div>
<br/>
<div class="field">
  <%= form.label :new_category, 'Enter a new category' %>
  <%= form.text_field :new_category %>
</div>


<br> 
<div class="form_row">
<%= form.label :quote %>
<%= form.text_area :quote, :rows => 2, :cols => 40, :maxlength => 500 %>
</div>
<br> 
</fieldset>
<p>
<div class="form_row">
<%= form.submit 'Create' %>
</div>
</p>
<% end %>

app/views/quotations/_quotation.html.erb
<h3>Quotation</h3>

<div class="quotation container">
  <p><strong style="color:red">Author:</strong> <%= quotation.author_name %></p>
  <p style="margin-left:10px;"><strong style="color:red">Category:</strong> <%= quotation.category.name %></p>
  <p style="margin-left:10px;"><strong style="color:red">Quote:</strong> <%= quotation.quote %></p>
</div>

app/views/quotations/import_xml.html.erb
<%= form_tag(import_xml_quotations_path, method: :post) do %>
  <div class="field">
    <%= label_tag 'xml_source', 'XML Source URL' %>
    <%= text_field_tag 'xml_source' %>
  </div>
  <div class="actions">
    <%= submit_tag 'Import' %>
  </div>
<% end %>

app/views/quotations/index.html.erb
<p style="color: green"><%= notice %></p>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

<h1 style="color:red;text-align:center">Quotations Main Page</h1>

<h3>Import Quotations from XML</h3>
<%= form_tag(import_xml_external_quotations_path, method: :post) do %>

  <div class="form_row">
    <%= label_tag :xml_url, 'XML URL:' %>
    <%= text_field_tag :xml_url, nil, placeholder: 'Enter XML URL' %>
  </div>
  <div class="form_row">
    <%= submit_tag 'Import' %>
  </div>
<% end %>
 <hr/>
 <%= form_tag(import_xml_quotations_path, method: :post) do %>
  <div class="form_row">
    <%= submit_tag 'Click to Import from Local xml File' %>
  </div>
<% end %>
 <hr/>
 <br/>
<h2>Please Search Here</h2>
<%= form_tag(search_quotations_path, method: :get) do %>
  <div class="form_row">
    <%= text_field_tag :query, params[:query], placeholder: 'Enter a word to search' %>
    <%= submit_tag 'Search' %>
  </div>
  <br/>
  <hr/>
  <br/>
<% end %>

<hr/>
<%= link_to "Create New Quotation", new_quotation_path %>
<hr/>

<% if @query.present? %>
<div>
<%= link_to "Back", quotations_path %>
</div>
  <h2>Search Results for "<%= @query %>"</h2>

<% end %>
<h2>Quotation List:</h2>

<% @quotations.each do |quotation| %>
  <%= render quotation %>
<% end %>










<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

app/views/quotations/new.html.erb
<h1>New Quotation</h1>

<%= render 'form', quotation: @quotation, existing_categories: @existing_categories %>


<div>
  <%= link_to "Back to Quotations", quotations_path %>
</div>